import { Inter } from "@next/font/google";
import { useTranslations } from "next-intl";
import Head from "next/head";
import { Footer } from "./Footer";
import { Nav } from "./Nav";

const inter = Inter({ subsets: ["latin"] });

type PageProps = {
  children: React.ReactNode;
  title: string;
};

export const Page = ({ children, title }: PageProps) => {
  const t = useTranslations("Page");
  const fullTitle = `${title} | ${t("school_name")}`;

  return (
    <>
      <Head>
        <title>{fullTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <Nav />
        <main className="px-2">{children}</main>
        <Footer />
      </div>
    </>
  );
};

Page.messages = ["Page", Nav.messages, Footer.messages];
